### ISSUE TITLE
[BUG] Environment sales undefined

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/pdf-generator#6]
When trying to generate a sales report pdf
`ERR API Error on /pdf/report/user: Ran into an issue when converting to PDF. 

Error: LaTeX Syntax Error
! LaTeX Error: Environment sales undefined.
!  ==> Fatal error occurred, no output PDF file produced! | timestamp=2024-09-17T11:10:53.082Z`

**Comment by JustSamuel** [comment]
This is part of templates, not pdf-gen.
